apiVersion: v1
kind: Service
metadata:
  name: grafana-ip-service
  namespace: default
  annotations:
      prometheus.io/scrape: 'true'
      prometheus.io/path:   /metrics
      prometheus.io/port:   '3000'
spec:
  type: ClusterIP 
  selector:
    component: grafana
  ports:
  - port: 3000
    targetPort: 3000
